from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from models.schemas import EmissionOutput, OptimizationResponse
import io

class ReportService:
    def generate_pdf(self, company_name: str, prediction: EmissionOutput, optimization: OptimizationResponse) -> bytes:
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter)
        styles = getSampleStyleSheet()
        story = []

        # Title
        title_style = styles['Title']
        story.append(Paragraph(f"Sustainability Report for {company_name}", title_style))
        story.append(Spacer(1, 12))

        # Executive Summary
        story.append(Paragraph("Executive Summary", styles['Heading2']))
        summary_text = f"This report provides an analysis of your company's carbon footprint. The total estimated emission is <b>{prediction.emission_kg:.2f} kg CO2e</b>."
        story.append(Paragraph(summary_text, styles['Normal']))
        story.append(Spacer(1, 12))

        # Prediction Details
        story.append(Paragraph("Emission Analysis", styles['Heading2']))
        story.append(Paragraph(prediction.explanation, styles['Normal']))
        story.append(Spacer(1, 12))

        # Optimization Suggestions
        story.append(Paragraph("Optimization Recommendations", styles['Heading2']))
        
        data = [["Category", "Suggestion", "Potential Savings (kg)"]]
        for opt in optimization.suggestions:
            data.append([opt.category, opt.suggestion, f"{opt.potential_saving_kg:.2f}"])
        
        # Add total savings
        data.append(["TOTAL", "", f"{optimization.total_potential_savings:.2f}"])

        t = Table(data)
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, -1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        story.append(t)
        story.append(Spacer(1, 12))

        # Disclaimer
        story.append(Paragraph("Generated by Carbon Emission Intelligence Assistant", styles['Italic']))

        doc.build(story)
        buffer.seek(0)
        return buffer.read()
